source 'https://rubygems.org'

gem 'rails', '4.0.1'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'twitter-bootstrap-rails'
gem 'slim'

gem 'therubyracer'

gem 'httparty'
gem 'redis'

gem 'jquery-rails'
gem 'turbolinks'
